--[[
                                      \\\\///
                                     /       \
                                   (| (.)(.) |)
     .---------------------------.OOOo--()--oOOO.---------------------------.
     |                                                                      |
     |  @file-author@'s DadGratz Addon for World of Warcraft
     ######################################################################## ]]
--   ## Let's init this file shall we?
-- Imports
local _G = _G
local me, ns = ...
local addon = ns
--local addon = LibStub("LibInit"):NewAddon(ns, me, true, "AceConsole-3.0", "AceEvent-3.0", "AceTimer-3.0")
local L = addon:GetLocale()
-- End Imports
--[[ ######################################################################## ]]
--   ## Do All The Things!!!
DG_globals.jokesSafe = {
  "Well, %s, that thar be a nice achievement you got there!",
  "Dude, %s, thats awesome!",
  "Magnifico, %s!",
  "Great Achievement, %s! keep up the aweshumm :D",
  "Well done %s!!",
  "I do believe that %s got a nice cheevo!",
  "Glad to see the achievement, %s! nice one!",
  "OOooooh nice achievement %s!! :)",
  "WOOOHOOO!! well done that %s!",
  "Achievement score = Achievement score + Achievement amount! :D",
  "oooooh nice achieve, %s! :)",
  "Every time %s gets an achievement a penguin wants to hug them!",
  "Every time %s gets an achievement a rainbow forms!",
  "A great achievement by a great person! :)",
  "Every time %s gets an achievement a dolphin jumps over a double rainbow!",
  "That achievement is beaten only by marshmallows, coated in chocolate and sprinkled with choc chips! ... but only just!",
  "If you achieve it, Achievements will come! ... or baseball fields :/",
  "%s deserves a medal... oh wait, we call them achievements... WELL DONE!! :D",
  "%s got an achievement! .. showing today on front row! [anyone who got that reference deserves a cookie!!]",
  "Thats a nice achievement, really, truly, very... well done, %s! Most impressive! :)",
  "GRATZAMONDO, %s!! :D",
  "Perfectly executed achievement, %s! Top notch, well done!",
  "Thats plenty brilliant, %s! nice one!",
  "AHA, the cheevo game is afoot!",
  "If that were a trick shot it'd break the table for being so epic!",
  "It's a great day for a great achievement such as that one!",
  "At the most opportune time, came the most awesome achievement",
  "You walk through the achievements with the majesty of an ocean liner cruising the waves",
  "We see you like achievements, we know you like grats, so here is one for you now :D",
  "May the grats be with you!",
  "go for the gold text! the gold text is , the gold text is wise!",
  "3 blind mice, see how they run... they saw your epic achievement appear, they ran from the clock in panic and fear, they ran in the road and got squished my dear..",
  "Doing well, keep it up!",
  "Plenty of fun to be had when getting those achievements, we all should venture more into that side of things.. make a day of it even? :)",
  "Wow such awesome, many Congrats!!",
  "!gratz!",
  "Epically glorious Achievement!",
  "well done on that one! :)",
  "awesome",
  "Pukkachieve :D",
  "nice achieve!",
  "top achieve!",
  "Thats great dude well done",
  "brilliant achieve!",
  "We love achievements here!",
  "nice one!",
  "cool achieve!",
  "Great achievement!!!",
  "Ah yes, Well done! nice achievement :D",
  "Well thats certainly a great achievement, well done!",
  "Achievements, achievements everywhere! AND ITS AWESOME!",
  "If i had a rainbow, and that rainbow had kittens and those kittens had rainbows of their own that had kittens, that'd be your achievement!!",
  "Glad to see another achievement :)",
  "Achievements are the key to Azeroth's soul, and you enrich it so with that one :)",
  "In all the lands of Azeroth, be it highest mountain or deepest sea, the rivers would always swell, the life they brought and the animals that were drawn to it, like achievements to you it was excellent!",
  "I know of at least 100 people who got that achievement, but none of them did it with as much grace as that! well done!!! :P",
  "If Illidan saw that he'd HAVE to admit that YOU were prepared!",
  "Denver, the last dinosaur, saw your achieve and he danced on the floor!",
  "This Grats brought to you by pink furry bunnies dancing in a circle and chanting your name for that epic achievement!",
  "Dats an amazin' achieve yo!",
  "And this is what i'm talking about, GREAT ACHIEVEMENT!, like really well done!!! :)",
  "By Azeroth! you really rocked that achievement!!",
  "Wibble wobble wibble wobble, achievement on the plate! congrats! :D",
  "Achievements, for getting, sharing and boasting about.. or at least that one is!",
  "Look at the sparkly achievement that just happened!!",
  "Achievement detected.. Grats initiated!",
  "NICE!!",
  "Not even Deathwing would argue that achievement! Congrats!",
  "Achievement cometh, and grats shalt follow! congratulations!",
  "Up through the darkness the shadowy figure arose, it looked at you... it came ever closer!... it shook your hand and congratulated you on that achievement. well done!!",
  "... and the grats was to be had for that achievement.. they partied, stayed up late... and in the morning.. they made waffles!.. congrats!",
  "The textual proof of your said accomplishment is acknowldged in this congratual fashion.",
  "Ah Yes, perfectly executed achievement, well done!",
  "YAY nice achieve!",
  "!!! CONGRATS !!!",
  "Happy Birth... DOH.. i mean congratulations on your achievement!",
  "Congratulations on that achievement!",
  "Splendid! Keep up the achievements!",
  "I, ".. UnitName("player").. " salute that achievement Wholely!",
  "Well done that one!",
  UnitName("player").. " like's your achievement, ".. UnitName("player").. " give you grats!",
  "GRATZAMONDO!!",
  "Fantastic achievement! from your friendly nighbourhood ".. UnitName("player"),
  "Your efforts have not gone un-noticed, congratulations! :D",
  "The wisps of Moonglade chanted your name as you got THAT achievement!",
  "The clarity of your achievement echoes through the lands! well done!",
  "Do you chase waterfalls? rivers? lakes? That achievement has music written all over it!",
  "Whose the tank?.... uh i mean CONGRATULATIONS! ... whats the mage?.... i dont know.... HE'S THE PRIEST!",
  "Congrats on the Achievement! :)",
  "Like a rocket, that achievement soared! Great one!",
  "That achievement was like a bright firework, for all to see!",
  "Nice and clean, NICE... and... CLEAN... achievement!",
  "Always let your achievement be your guide.. no wait... ... yeah achievement yeah! :D",
  "Achievements shall set you free... especially that one!  JOB!!",
  "As we walk through the valley of the achievements of fun, i take a look at my Char and realise i like every single one ...",
  "Is it a bird!? is it a plane! NO its an achievement! But they're one and the same!!",
  "DUUUUUUUDE! nice!",
  "Nice Achieve, PARTY TIME! Excellent! *cue air guitar*",
  "Achievement be like 'YO CHECK ME OUT' and we're like 'DUDE! We know man, awesome!!'",
  "Some may hunt and some may stroll, some may encounter them as they roll, be sure to note, we don't care how, we're just glad there's another now! Gratz!",
  "Maximum Congratulations my fellow guildonian!",
  "Throwing forward my greatest applause for that achievement!",
  "All the critters in the area are celebrating that achievement, as are we!",
  "May all your mounts crowd around you in tribute for that single achievement alone!",
  "If that achievement were any brighter it would sparkle in the sky!",
  "Your achievement will resonate through time and space with grace!",
  "Let loose of your hatred, feeel the warm embrace of achievements....... aaahhhhhhh :D",
  "The magnitude of your achievement will ring through the ages... congrats! :D",
  "Always let your achievement be your guide!",
  "Wellius Dunnikus!",
  "Achievement Detected! Grats initiated! ... CONGRATS! :D",
  "oooOOOOoooooh NICE!",
  "Achievement meet Grats, Grats meet Achievement! ... aww, look how good they are together!",
  "THAT ROCKS... great achievement!!",
  "I say, what a lovely achievement you got! set it down over there with the rest of them, theres a good guildy. congrats btw! :D",
  "Gotta collect-em all!! .. no wait i mean well done!",
  "Have a cookie for THAT achievement! Well earned!",
  "Have 10 cookies for THAT achievement!! Great Job!",
  "An achievement walks into a box.... THE CHATBOX! congrats!",
  "Your accomplishment is acknowledged by this text stating about it! nice one!",
  "EJECTO CHEEVO CUZZZ!! nice! :D",
  "*SCHHH* ... this is Grats, permission to land ... *SCHHH* Ground control here, you're clear to land.. bring her home!... *SCHHH*",
  "The achievement bus is coming and everybodys jumping, stormwind to undercity, the grats are gettin busy..",
  "..and, as we celebrate their achievement, another guildy would like to say a few words.. most likely just one word and sound like 'mats', but there we go!",
  "And now, we see the achievement.. see it's Yellow glow as it tries to attract a mate.. the Grats as they are commonly known, come out in numbers to show their superiority.. only one will be worthy!",
}
--[[
     ########################################################################
     |  Last Editted By: @file-author@ - @file-date-iso@
     |  @file-revision@
     |                                                                      |
     '-------------------------.oooO----------------------------------------|
                              (    )     Oooo.
                              \  (     (    )
                               \__)     )  /
                                       (__/                                   ]]
